kind: pipeline
type: docker
name: default

steps:
- name: Format
  image: rustbuilder
  pull: never
  commands:
    - cargo fmt -- --check
 
- name: Clippy 
  image: rustbuilder
  pull: never
  commands:
    - cargo clippy --all --all-targets --all-features -- -Drust-2018-idioms -Ddeprecated
    #- cargo clippy --all --all-targets --all-features -- -Dwarnings -Drust-2018-idioms -Ddeprecated

- name: Build
  image: rustbuilder
  pull: never
  commands:
  - cargo build --release
