replicaCount: 1
fullnameOverride: 'postgresql'

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 15.4.0-debian-11-r10
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  postgresql:
    auth: # todo: manage secrets using vault
      postgresPassword: "password"
      username: ""
      password: ""
      database: ""
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""
    service:
      ports:
        postgresql: ""

serviceAccount:
  create: true
  name: "postgresql"
  automountServiceAccountToken: true
  annotations: {}
architecture: standalone
containerPorts:
  postgresql: 5432
shmVolume:
  enabled: true
  sizeLimit: ""
postgresqlDataDir: /bitnami/postgresql/data
postgresqlSharedPreloadLibraries: "pgaudit"



