apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: checks
    - port: {{ .Values.grpc.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
