global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "consumer-docker"
    static_configs:
      - targets: ["consumer:8002"]
  - job_name: "consumer"
    static_configs:
      - targets: [ "host.docker.internal:8002" ]